# Generated by Django 4.2.8 on 2024-01-31 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_stories_id_stories_uid_delete_storyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='uid',
        ),
        migrations.AddField(
            model_name='stories',
            name='id',
            field=models.BigAutoField(auto_created=True, default=datetime.datetime(2024, 1, 31, 10, 54, 13, 139119, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
