# Generated by Django 4.2.8 on 2024-01-31 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_user_storyprofile_username'),
        ('post', '0007_rename_uid_storyprofile_uids'),
    ]

    operations = [
    ]
