# Generated by Django 4.2.8 on 2024-01-31 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0005_alter_storyprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryProfile',
        ),
    ]
